#ifndef _GRAMMAR_PROGRAM_H_
#define _GRAMMAR_PROGRAM_H_
#include "common.h"
#include "../util/exception.h"
void programme(void);
void segment(void);
void type(void);
void funtail(void);
void def(void);
void idtail(void);
void vardef(void);
void init(void);
void deflist(void);
void defdata(void);
void paradata(void);
void paradatadetail(void);
void paralist(void);
void para(void);
void expr(void);
void block(void);
#endif